### ISSUE TITLE
255fps

### ISSUE THREAD

**Issue by Dragonix1999** [masagrator/NX-FPS#1]
installed NX-FPS 0.3 but every game I tried showed 255fps (doom 64 and ARK)

**Comment by masagrator** [comment]
Maybe more info about your Switch, upload SaltyNX log, etc? 
Your post doesn't help at all.

**Comment by masagrator** [comment]
And ffs, don't write your issues in every possible place.

**Comment by Dragonix1999** [comment]
I am using homebrew only since a few weeks so I don’t know too much about it. I am using the latest version of Kosmos. How can I find the SaltyNX log?

**Comment by masagrator** [comment]
In SaltySD folder

**Comment by Dragonix1999** [comment]
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: Failed to load ELF `sdmc:/SaltySD/saltysd_proc.elf'! Error 1
Spawner: ELF load failed with ffffffff

**Comment by masagrator** [comment]
You have too much sysmodules. Delete anything that you are not using and I recommend also to delete emuiibo.

**Comment by Dragonix1999** [comment]
I deleted everything I didnt need but it still shows 255

**Comment by masagrator** [comment]
And what log shows?

**Comment by Dragonix1999** [comment]
And tesla is the only sysmodule which is turned on when I check my Kosmos Toolbox

**Comment by Dragonix1999** [comment]
Still the same log

**Comment by masagrator** [comment]
It doesn't matter if they are turned off, they need to be physically deleted.

Are you sure you have downloaded SaltyNX-0.1.2a.zip, not only KIP or NSP?

**Comment by Dragonix1999** [comment]
Yes I am sure. Should I also delete EdiZon?

**Comment by masagrator** [comment]
EdiZon is not a sysmodule.
What you are using? KIP or NSP?

**Comment by masagrator** [comment]
The best solution would be to delete entirely Kosmos and start with fresh Atmosphere. I hate to help when I don't know what shit people have on their sdcards and Kosmos Has shitton of stuff + Idk how competent is the person using that and if he really knows what is he doing. Putting fresh Atmosphere helps to start from the same point.

**Comment by Dragonix1999** [comment]
I am using .kip .From which folder do I have to delete sysmodules? Maybe I didnt delete them right

**Comment by masagrator** [comment]
Sysmodules are in
`atmosphere/contents`
Don't delete all as some of them are CFW sysmodules (just compare Atmosphere github release with what you have and delete everything additional in this folder)
You can also try NSP instead of KIP.

**Comment by Dragonix1999** [comment]
I tried the NSP and now it works... thank you so much!
