### ISSUE TITLE
Incompatible with Plants vs. Zombies: Battle for Neighborville (Crashes on Startup)

### ISSUE THREAD

**Issue by NoOneOfSignificance** [masagrator/NX-FPS#11]
After launching the game and seeing the Nintendo Switch logo in the bottom-right corner for a few seconds the game crashes. I'm running on the latest Nintendo Switch firmware and atmosphere/saltynx/nx-fps releases as of 6/8/22. It's a 64-bit game and uses the NVN api (from what I've been able to gather). Logs are provided below.

[saltysd.log](https://github.com/masagrator/NX-FPS/files/8865560/saltysd.log)
[saltysd_core.log](https://github.com/masagrator/NX-FPS/files/8865561/saltysd_core.log)

**Comment by masagrator** [comment]
https://github.com/masagrator/SaltyNX/pull/20

I forgot about checking this game for few reasons.
