### ISSUE TITLE
No FPS on any game on Deepsea CFW

### ISSUE THREAD

**Issue by czerwinski76** [masagrator/NX-FPS#12]
Since several month, I don't know why but I can't have any FPS count on my Switch.

Status-Monitor-Overlay > LATEST
SaltyNX  > LATEST
NX-FPS > LATEST

**Comment by masagrator** [comment]
Stop using deepsea. I am not supporting custom CFW packages.

**Comment by czerwinski76** [comment]
How can I use your work without having a CFW please ?
