### ISSUE TITLE
Wont work on 10.0.1

### ISSUE THREAD

**Issue by lajax01** [masagrator/NX-FPS#2]
I use this sucessfuly on 9.2 fw, with SaltyNX.
Now I update fw, update everything, but no luck.
Fps counter show up, but static 255 fps.. :/
Please advise.

**Comment by masagrator** [comment]
Well:
- CFW
- all used sysmodules with versions
- is SaktyNX you are using the newest one
- Games you have tested
- Is SaltyNX-Tool showing that SaltyNX is properly injected

Start from this.

**Comment by lajax01** [comment]
Sorry it take so long to reply. Real life.. :)
CFW Atmosphere latest with all KIP_Paches Version: 0.12.0 based on 10.0.1 OFW
List of sysmodules: sys-clk latest (+ovl) version: 0.13.1 (nothing else)
SaltySD version: 0.3.1a with all deppendencies (inside in plugin folder located NX-FPS 0.3)
In .overlays folder: ovlEdiZone (v1.1.0) (no cheats used at all), ovlmenu, Status-Monitor-Overlay (0.5.2), sys-clk-overlay (v1.1).
OVL loader is v1.0.5

**Comment by masagrator** [comment]
In SaltyNX-Tool first line is the most important.

So that means SaltyNX is not working for you.
Check if all files are put correctly.

**Comment by lajax01** [comment]
Ok. I will report back tomorrow. Thanks for the reply. ;)

**Comment by masagrator** [comment]
30+ days without reply. Closing.
