### ISSUE TITLE
Status-Monitor-Overlay 0.8.0 and NX-FPS 0.3 have other functions

### ISSUE THREAD

**Issue by h469211620** [masagrator/NX-FPS#27]
Status-Monitor-Overlay 0.8.0 and NX-FPS 0.3，It is very useful to automatically load cheats when opening the Status-Monitor-Overlayd. For example, adjusting image quality and frame count（1080p or 60fps）. There is no need to open EdiZone or Breeze after the game starts, which is very convenient. The subsequent versions will not work, can we add a branch in the version to preserve this feature

**Comment by masagrator** [comment]
Those features never existed in official Status Monitor. Whatever you were using was probably some fork of this overlay. Ask author of that fork for those features, not me.

**Comment by h469211620** [comment]
NX-FPS 0.4 ，Move writing data into SaltyNX SharedMemory. 
It should be because of this reason that the above functions cannot be implemented in future versions.

**Comment by h469211620** [comment]
> Those features never existed in official Status Monitor. Whatever you were using was probably some fork of this overlay. Ask author of that fork for those features, not me.

Those features never existed in official Status Monitor.
I did not use any other branches. Perhaps this feature was an accident. Sorry, I don't know much English. The above are all translation software used, hoping to express my meaning

**Comment by masagrator** [comment]
> It should be because of this reason that the above functions cannot be implemented in future versions.

And I don't plan to change that as this allows more flexibility in using Status Monitor while debugging games to make cheats and mods.
With older versions it was not possible.
