### ISSUE TITLE
Getting 254 fps with Persona 5 Strikers

### ISSUE THREAD

**Issue by ManuelM0** [masagrator/NX-FPS#4]
I don't know if this is still being worked on but could Persona 5 Strikers be added to the list of compatible games?

**Comment by masagrator** [comment]
There is no "list of compatible games". There is only list of not compatible games.
Persona 5 Strikers works fine with FPS Counter. 
Check if you installed plugin correctly and SaltyNX is enabled jn SaltyNX-Tool.
