### ISSUE TITLE
Unsupported game

### ISSUE THREAD

**Issue by Arch9SK7** [masagrator/NX-FPS#5]
Using your latest build release. It seems that the game Ty The Tasmanian Tiger HD on switch doesnt seem to be supported. Upon loading it just shows and stays at 0.00fps 

If there is anyway to get support added and or anyway i can help. I can also provide the game if you need as well. Its a rather small game in size.

**Comment by masagrator** [comment]
Be sure logs are enabled (they are by default, so if you didn't change anything they should be generated)
Delete `saltysd.log` and `saltysd_core.log` from `SaltySD` folder, run game again and when you will see that game is showing 0 FPS even when you see clearly that game is showing something, close game, get `saltysd.log` and `saltysd_core.log` and upload both of those files here.

**Comment by Arch9SK7** [comment]
[saltysd.log](https://github.com/masagrator/NX-FPS/files/6528500/saltysd.log)
[saltysd_core.log](https://github.com/masagrator/NX-FPS/files/6528501/saltysd_core.log)
done. here you go

**Comment by Arch9SK7** [comment]
@masagrator

**Comment by Arch9SK7** [comment]
[saltysd.log](https://github.com/masagrator/NX-FPS/files/6528514/saltysd.log)
sorry this is the one thatshows up for playing only the game showing as zero

**Comment by Arch9SK7** [comment]
it doesnt even show the games tid showing in the log

**Comment by masagrator** [comment]
"SaltySD: ARM32 applications plugins are not supported, aborting bootstrap..."
Game is 32-bit. It shows 0 FPS probably because you don't give a chance for Status Monitor to delete leftovers when closing game and it tries to read value from memory offset that belonged to last compatible game running.

**Comment by Arch9SK7** [comment]
So should I be clearing any files when switching games or is it alright just closing a game and waiting a little bit before opening the next one?

**Comment by masagrator** [comment]
Status Monitor is clearing stuff in one of two moments:
- If Status Monitor is running and you are closing a game, when FPS counter stops showing, it deleted all temp data.
- If Status Monitor will be opened when no game is running, after checking that no game is running it will delete all temp data that are left.

**Comment by Arch9SK7** [comment]
okai well no need to be rude. i have let it clear all temp data and still the game doesnt show as supported so thanks for your help m8

**Comment by masagrator** [comment]
Idiotproof is normal term, not a diss...
This is first time I see someone was offended by using this term.
