### ISSUE TITLE
Not count FPS on MH Rise

### ISSUE THREAD

**Issue by lerd2805** [masagrator/NX-FPS#8]
Hi,

I'm testing this FPS counter on MH Rise and is not working, stay on 0.00 all the time.

Thanks for creating this great tool.

**Comment by masagrator** [comment]
What version of game you have? Last time I was testing iirc on 3.2.1 and it was working perfectly fine.

0.0 sounds weird since it should be 254 or 255 if it's not compatible

**Comment by lerd2805** [comment]
> What version of game you have? Last time I was testing iirc on 3.2.1 and it was working perfectly fine.
> 
> 0.0 sounds weird since it should be 254 or 255 if it's not compatible

Nevermind, is working now. I think was a partially bug, restarted the console and works fine.
